name: contacts
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.6.1
  flutter_google_places: ^0.1.4+1
  shared_preferences: ^0.4.3
  json_annotation: ^2.0.0
  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1
  url_launcher: ^4.0.1
  image_picker: ^0.4.10
  sqflite: ^0.12.2+1
  http: ^0.12.0
  intl: ^0.15.7

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

dev_dependencies:
  build_runner: ^1.1.2
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
